openapi: 3.0.1
info:
  title: Jira GPT Agent API
  version: 1.0.0
servers:
  - url: https://jira-gpt-agent.onrender.com
paths:
  /create-jira-issue:
    post:
      operationId: createJiraIssue
      summary: Create a new Jira ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - projectKey
                - summary
                - description
              properties:
                projectKey:
                  type: string
                  example: AAD
                  description: The Jira project key
                summary:
                  type: string
                  example: Add health checks to all services
                  description: One-line summary of the task
                description:
                  type: string
                  example: Ensure all deployed services expose a /healthz endpoint
                  description: Detailed explanation of the task
                issueType:
                  type: string
                  example: Task
                  description: Type of Jira issue (Task, Bug, Story)
                estimate:
                  type: number
                  example: 1.5
                  description: Estimated number of hours to complete
                assignee:
                  type: string
                  example: Yuval Nahon
                  description: Full display name of the person to assign
                epic:
                  type: string
                  example: AAD-25
                  description: Epic issue key this task belongs to
      responses:
        '200':
          description: Jira ticket created
          content:
            application/json:
              schema:
                type: object
                properties:
                  issueKey:
                    type: string
                    example: AAD-123
                  issueUrl:
                    type: string
                    example: https://yourcompany.atlassian.net/browse/AAD-123
