services:
  - type: web
    name: jira-gpt-agent
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: JIRA_EMAIL
        value: your-email@example.com
      - key: JIRA_API_TOKEN
        value: your-api-token
      - key: JIRA_BASE_URL
        value: https://yourcompany.atlassian.net
